/*
 * This file was automatically generated by EvoSuite
 * Mon Oct 09 05:53:02 GMT 2017
 */

package com.varsh.tech.springboot.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.varsh.tech.springboot.util.CustomErrorType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CustomErrorType_ESTest extends CustomErrorType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CustomErrorType customErrorType0 = new CustomErrorType((String) null);
      String string0 = customErrorType0.getErrorMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CustomErrorType customErrorType0 = new CustomErrorType("&FK%K*|7h");
      String string0 = customErrorType0.getErrorMessage();
      assertEquals("&FK%K*|7h", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CustomErrorType customErrorType0 = new CustomErrorType("");
      String string0 = customErrorType0.getErrorMessage();
      assertEquals("", string0);
  }
}
